apiVersion: v1
kind: Service
metadata:
  name: service-state-check-svc
  labels:
    appName: service_state_check
    appType: flaskApp
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    appName: service_state_check
    appType: flaskApp
  type: NodePort
